curl -X POST http://localhost:8080/api/books/Spring
curl -X POST http://localhost:8080/api/books/JEE
curl -X GET http://localhost:8080/api/books/ISBN1
curl -X DELETE http://localhost:8080/api/books/ISBN1
curl -X PUT -H "Content-Type: application/json" -d@update.json http://localhost:8080/api/books/ISBN2

curl -X GET http://localhost:8080/api/books/compact-ISBN1
curl -X GET http://localhost:8080/api/books/isbns
